services:
  - type: web
    name: neonspark-ai
    env: python
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: python start_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    plan: free
